# Generated by Django 5.0 on 2023-12-19 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('logo', models.ImageField(upload_to='logos/')),
                ('monday', models.CharField(max_length=255)),
                ('tuesday', models.CharField(max_length=255)),
                ('wednesday', models.CharField(max_length=255)),
                ('thursday', models.CharField(max_length=255)),
                ('friday', models.CharField(max_length=255)),
                ('saturday', models.CharField(max_length=255)),
                ('sunday', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('district', models.CharField(max_length=255)),
                ('full_address', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=255)),
                ('facebook', models.CharField(max_length=255)),
                ('instagram', models.CharField(max_length=255)),
                ('tiktok', models.CharField(max_length=255)),
                ('youtube', models.CharField(max_length=255)),
                ('discord', models.CharField(max_length=255)),
                ('telegram', models.CharField(max_length=255)),
                ('main_price', models.IntegerField()),
                ('main_visit', models.CharField(max_length=255)),
                ('custom_price', models.CharField(max_length=255)),
                ('map_link', models.CharField(max_length=255)),
                ('views', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='logos/')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='places.place')),
            ],
        ),
    ]
