# Generated by Django 5.0 on 2023-12-19 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='monday',
            field=models.TimeField(max_length=255),
        ),
    ]
