# Generated by Django 5.0 on 2023-12-19 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_alter_place_monday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='friday',
        ),
        migrations.RemoveField(
            model_name='place',
            name='monday',
        ),
        migrations.RemoveField(
            model_name='place',
            name='saturday',
        ),
        migrations.RemoveField(
            model_name='place',
            name='sunday',
        ),
        migrations.RemoveField(
            model_name='place',
            name='thursday',
        ),
        migrations.RemoveField(
            model_name='place',
            name='tuesday',
        ),
        migrations.RemoveField(
            model_name='place',
            name='wednesday',
        ),
        migrations.AddField(
            model_name='place',
            name='friday_close',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='friday_open',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='monday_close',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='monday_open',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='saturday_close',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='saturday_open',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='sunday_close',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='sunday_open',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='thursday_close',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='thursday_open',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='tuesday_close',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='tuesday_open',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='wednesday_close',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='wednesday_open',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
