# Generated by Django 5.0 on 2023-12-19 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_remove_place_friday_remove_place_monday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='discord',
            field=models.URLField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='facebook',
            field=models.URLField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='instagram',
            field=models.URLField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='map_link',
            field=models.URLField(max_length=255),
        ),
        migrations.AlterField(
            model_name='place',
            name='telegram',
            field=models.URLField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='tiktok',
            field=models.URLField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='youtube',
            field=models.URLField(max_length=255, null=True),
        ),
    ]
