<<<<<<< HEAD
# Generated by Django 4.2.7 on 2023-12-23 09:30
=======
# Generated by Django 4.2.7 on 2023-12-22 08:22
>>>>>>> f1b971eac74c3168742dc358cb87411e6d042ea6

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
<<<<<<< HEAD

    dependencies = [
        ('places', '0006_alter_place_id_alter_place_number'),
=======
    dependencies = [
        ("places", "0006_alter_place_id_alter_place_number"),
>>>>>>> f1b971eac74c3168742dc358cb87411e6d042ea6
    ]

    operations = [
        migrations.AlterField(
<<<<<<< HEAD
            model_name='photo',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='places.place'),
=======
            model_name="photo",
            name="place",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="photos",
                to="places.place",
            ),
>>>>>>> f1b971eac74c3168742dc358cb87411e6d042ea6
        ),
    ]
